version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    #command:
    #- --config.file=/etc/prometheus/prometheus.yml
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--log.level=debug",
      "--storage.tsdb.path=/prometheus",
      "--storage.tsdb.retention=1h",
      "--web.enable-admin-api",
    ]
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on: 
    - prometheus
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8082:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
  node:
    image: prom/node-exporter:latest
    container_name: node
    ports:
    - 9100:9100

  # redis-commander:
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   environment:
  #   - REDIS_HOSTS=local:redis:6379
  #   ports:
  #   - "8085:8081"

volumes:
    prometheus_data: {}
    grafana_data: {}
networks:
  default:
    external:
      name: myNetwork
