scrape_configs:
- job_name: cadvisorhugo
  scrape_interval: 5s
  static_configs:
  - targets:
    - docker.for.mac.localhost:8082
- job_name: prometheus
  scrape_interval: 15s
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  scrape_interval: 15s
  static_configs:
  - targets:
    - docker.for.mac.localhost:9100
- job_name: jmeter-metrics
  scrape_interval: 15s
  static_configs:
  - targets:
    - docker.for.mac.localhost:9270
- job_name: mongodb
  scrape_interval: 5s
  static_configs:
  - targets:
    - docker.for.mac.localhost:9001

- job_name: hapifhir
  scrape_interval: 5s
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - docker.for.mac.localhost:8184


